services:
  - type: web
    name: tg-downloader
    env: python
    buildCommand: |
      apt-get update
      apt-get install -y ffmpeg
      pip install -r requirements.txt
    startCommand: python bot.py
